blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/KevinMwita7/DevOpsStarter/discussions
    about: Please use GitHub Discussions for questions and general support.
