name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run Unit Tests with Coverage
      run: |
        coverage run -m pytest tests/
        coverage report
        coverage xml

    - name: Publish Coverage
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: coverage.xml

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always
          deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          retry-on-snapshot-warnings: true
          base-ref: ${{ github.base_ref }}
          head-ref: ${{ github.head_ref }}
