name: Release Docker Image

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      sha_tag:
        description: 'The Git SHA tag of the image to release (e.g. 7d4d42b).'
        required: true
      release_tag:
        description: 'The new release tag (e.g. 1.2.3).'
        required: true
      environment:
        description: 'The target environment for deployment.'
        type: choice
        required: true
        default: 'production'
        options:
          - 'production'
          - 'staging'
          - 'qa'
env:
  IMAGE_NAME: kevinmwita7/helloworld
  SHA_TAG: kevinmwita7/helloworld:${{ github.event.inputs.sha_tag }}
  RELEASE_TAG: kevinmwita7/helloworld:${{ github.event.inputs.release_tag }}


jobs:
  promote-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          
      - name: Pull and re-tag Docker image
        run: |
          docker pull ${{ env.SHA_TAG }}
          docker tag ${{ env.SHA_TAG }} ${{ env.RELEASE_TAG }}

      - name: Push the new release tag
        run: docker push ${{ env.RELEASE_TAG }}

      - name: Deploy to production
        if: github.event.inputs.environment == 'production'
        run: |
          echo "Deploying ${{ env.RELEASE_TAG }} to production..."
          # Add your production deployment logic here.
          # This could be a call to a deployment tool like Terraform.
